Changes to be able to build as Java 11 project
jQAssistant/jqa-core-framework pull request #69
Opened 2022-11-22 12:04 UTC by obfischer

Changes to the project to be able to run it as Java 11 application.

2022-11-24 15:05 UTC, StephanPirnbaum commented on pom.xml
> +            <dependency>
For what is this needed?

2022-11-24 15:05 UTC, StephanPirnbaum commented on pom.xml
> +            <dependency>
For what is this needed?

2022-11-29 13:42 UTC, DirkMahler requested changes

2022-11-29 13:42 UTC, DirkMahler commented on pom.xml
> +                <groupId>com.sun.xml.bind</groupId>
This managed dependency not necessary, there's already the glassfish JAXB impl on the classpath. Should be removed.

2022-11-29 15:52 UTC, merged